source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
# gem 'rails', '4.2.1'
gem 'rails', '4.2.4'

# gem 'pg'
# gem 'mysql2', '~> 0.3.20'
gem 'sqlite3', '~> 1.3', '>= 1.3.11'

gem 'rails_12factor', group: :production

gem 'sass-rails', '~> 5.0'

gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'i18n', '~> 0.7.0'
gem 'font-awesome-rails'
gem 'therubyracer'
gem 'less-rails'

gem 'twitter-bootstrap-rails', '>= 3.2.0', '< 3.2.2'

gem 'local_time'


gem 'chartkick'
gem 'bootstrap-datepicker-rails'

gem 'devise'

gem 'will_paginate', '~> 3.0.7'
gem 'will_paginate-bootstrap', '~> 1.0.1'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'bootstrap-multiselect-rails4', '~> 0.0.1'

# gem 'heroku-deflater' #, :group => :production

gem 'jquery_ujs_extended', '~> 0.0.3'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
gem 'jquery-turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'simple_form'

# gem 'rmagick'

# Rich Text Editor
# gem 'tinymce-rails'
# gem 'paperclip'
# gem 'redactor-rails'
# gem 'carrierwave'
# gem 'mini_magick'

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
gem 'unicorn'
gem "rack-timeout", require:"rack/timeout/base"
# gem 'thin'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'

  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  
end

