default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: admin@123
  host: localhost

development:
  <<: *default
  database: scoring_development

test:
  <<: *default
  database: scoring_test

production:
  <<: *default
  database: ENV['DATABASE_URL']
  username: ENV['DATABASE_URL']
  password: ENV['DATABASE_URL']
